### ISSUE TITLE
Obvious attack 

### ISSUE THREAD

**Issue by asdfhjasdhkjf** [JapanYoshi/Orelega#1]
I would like for you to take this entire branch down as it is an attack on big eared people. You wouldn't name your repo as something that included the N-word, unless you support racism, nor would you use the T-slur and/or transphobia. I feel attcked by it, being called "large-eared". It's simple human decency, please take this down.

**Comment by JapanYoshi** [comment]
>made account to do nothing but make this post
>butthurt at a [typographic term](https://www.fontsmith.com/blog/2016/06/29/the-a-z-of-typographic-terms#section-294)
>in esperanto, no less
gr8 b8 m8 i r8 8/8

“If we’re complaining the badness of two words, and you won’t even say one of the words, that’s the worse word.” —[John Mulaney](https://youtu.be/mg0UWxhJkfk)
